name: Testing

on:
  push:
    branches: [deploy/cicd]
  pull_request:
    branches: [main]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install dependencies
        run: |
          go mod download

      - name: Testing Usecase on Superadmin
        run: go test ./.../superadmin

      - name: Testing Usecase on Admin
        run: go test ./.../admin

      - name: Testing Usecase on Customer
        run: go test ./.../customer

      - name: Build
        run: go build -v ./...